name: carded
description: Your digital visiting card app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Networking
  http: ^1.2.0
  # Local storage (token + user cache only)
  shared_preferences: ^2.2.2
  # QR
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.6
  # Utilities
  image_picker: ^1.0.7
  uuid: ^4.3.3
  intl: ^0.19.0
  path_provider: ^2.1.2
  cupertino_icons: ^1.0.6
  flutter_contacts: ^1.1.9+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/logo.png"
  adaptive_icon_background: "#FFFFFF"  # ya apna brand color
  adaptive_icon_foreground: "assets/icon/fg.png"


flutter:
  uses-material-design: true
  assets:
    - assets/icon/